language: go

go: "1.10.1"

sudo: false

addons:
  - postgresql: "10"

services:
  - postgresql

before_script:
  - psql -c 'create database flockflow_dev;' -U postgres

install:
  - echo "nothing to install"

script:
  - go vet ./...
  - go test ./...
