language: go

go: "1.10.1"

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database flockflow_dev;' -U postgres

install:
  - echo "nothing to install"

script:
  - go vet ./...
  - go test ./...
