language: go

go: "1.10"

sudo: false

services:
  - postgresql

before_script:
  - psql -c 'create database flockflow_dev;' -U postgres

install:
  - echo "nothing to install"

script:
  - go vet ./...
  - go test ./...
