[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/athega/flockflow-server"
  go-version = "go1.10.1"
  install = [ "./..." ]
  ensure = "false"
